force-app/main/default/objects/Departamento__c/Departamento__c.object-meta.xml
<CustomObject>
    <label>Departamento</label>
    <nameField>
        <displayFormat>D-{000}</displayFormat>
        <label>ID de Departamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Departamento__c/fields/Nombre_de_Departamento__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Departamento__c</fullName>
    <label>Nombre de Departamento</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Departamento__c/fields/Oficina__c.field-meta.xml
<CustomField>
    <fullName>Oficina__c</fullName>
    <label>Oficina</label>
    <referenceTo>Oficina__c</referenceTo>
    <relationshipLabel>Departamentos</relationshipLabel>
    <relationshipName>Departamentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empleado__c/Empleado__c.object-meta.xml
<CustomObject>
    <label>Empleado</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>ID del Profesional</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empleados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empleado__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Departamento</label>
    <referenceTo>Departamento__c</referenceTo>
    <relationshipName>Profesionales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <label>E-mail</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Postulación</fullName>
            </value>
            <value>
                <fullName>Aprobación</fullName>
            </value>
            <value>
                <fullName>Contratado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/Fecha_de_Contratacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Contratacion__c</fullName>
    <label>Fecha de Contratación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oficina__c/Oficina__c.object-meta.xml
<CustomObject>
    <description>Objeto relacionado a las oficinas.</description>
    <label>Oficina</label>
    <nameField>
        <label>Nombre de Oficina</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oficinas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EmpleadoControllerTest.cls
@isTest
public class EmpleadoControllerTest {

    @isTest
    static void testFetchEmpleados() {
        // Crear la informacion para testear
       	Oficina__c of1 = new Oficina__c(Name = 'Oficina Test');
        insert of1;
        Departamento__c dp1 = new Departamento__c (Nombre_de_Departamento__c = 'Legal', Oficina__c=of1.Id);
        insert dp1;
        Empleado__c emp1 = new Empleado__c( Nombre__c = 'John', Apellido__c = 'Doe', Departamento__c=dp1.Id, E_mail__c = 'jdoe@test.com', Estado__c = 'Contratado', Fecha_de_Contratacion__c = Date.today());
        insert emp1;
        
        // Llamada al metodo a probar
        Test.startTest();
        List<Empleado__c> empList = EmpleadoController.fetchEmpleados();
        Test.stopTest();
        
        // Verificar el resultado
        System.assertEquals(1, empList.size());
        Empleado__c emp = empList[0];
        System.assertEquals(emp1.Id, emp.Id);
        System.assertEquals(emp1.Nombre__c, emp.Nombre__c);
        System.assertEquals(emp1.Apellido__c, emp.Apellido__c);
        System.assertEquals(emp1.E_mail__c, emp.E_mail__c);
        System.assertEquals(emp1.Estado__c, emp.Estado__c);
        System.assertEquals(emp1.Fecha_de_Contratacion__c, emp.Fecha_de_Contratacion__c);
    }
}