force-app/main/default/objects/Empleado__c/Empleado__c.object-meta.xml
<CustomObject>
    <label>Empleado</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>ID del Profesional</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empleados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empleado__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <label>E-mail</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Postulación</fullName>
            </value>
            <value>
                <fullName>Aprobación</fullName>
            </value>
            <value>
                <fullName>Contratado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/Fecha_de_Contratacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Contratacion__c</fullName>
    <label>Fecha de Contratación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empleado__c/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experiencia_Laboral__c/Experiencia_Laboral__c.object-meta.xml
<CustomObject>
    <description>Objeto para llevar control de las experiencia laborales.</description>
    <label>Experiencia Laboral</label>
    <nameField>
        <label>Nombre de la empresa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiencias Laborales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experiencia_Laboral__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <description>Cargo en el que trabajó.</description>
    <label>Cargo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experiencia_Laboral__c/fields/Experiencia_en_anos__c.field-meta.xml
<CustomField>
    <fullName>Experiencia_en_anos__c</fullName>
    <formula>FLOOR(( Fecha_de_Retiro__c -  Fecha_de_Ingreso__c ) / 365 )</formula>
    <label>Experiencia en años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Experiencia_Laboral__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <description>Experiencia laboral del profesional.</description>
    <label>Profesional</label>
    <referenceTo>Empleado__c</referenceTo>
    <relationshipLabel>Experiencias Laborales</relationshipLabel>
    <relationshipName>Experiencias_Laborales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Titulo_Academico__c/Titulo_Academico__c.object-meta.xml
<CustomObject>
    <description>Objeto encargado de llevar el registro del historial académico de los profesionales.</description>
    <label>Título Académico</label>
    <nameField>
        <label>Nombre de la Institución</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Títulos Académicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Titulo_Academico__c/fields/Nivel_Academico__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Academico__c</fullName>
    <description>Campo del nivel académico que cursó.</description>
    <label>Nivel Académico</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Licenciatura</fullName>
            </value>
            <value>
                <fullName>Diplomado</fullName>
            </value>
            <value>
                <fullName>Especialidad</fullName>
            </value>
            <value>
                <fullName>Maestría</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Titulo_Academico__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <description>Historial académico del profesional.</description>
    <label>Profesional</label>
    <referenceTo>Empleado__c</referenceTo>
    <relationshipName>Historiales_Academico</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EmpleadoController.cls
public class EmpleadoController {
    @AuraEnabled( cacheable = true )
    public static List<Empleado__c> fetchEmpleados(){
        return [
            SELECT Id, Name, Nombre__c, Apellido__c, E_mail__c, Estado__c, Fecha_de_Contratacion__c,
                (SELECT Nivel_Academico__c 
                FROM Historiales_Academico__r), 
                    (SELECT Experiencia_en_anos__c, Cargo__c 
                    FROM Experiencias_Laborales__r) 
            FROM Empleado__c
        ];
    }
}